name: 'Sonarqube Quality'
description: 'Sonarqube Quality Gate Status Checked'
inputs:
  token:
    description: "Sonar Login Token"
    required: true
  url:
    description: "Sonar Server url"
    required: true
runs:
  using: "composite"
  steps:
    - name: sonarScript.sh
      shell: bash
      run: |
        ce_task_id=AXihM-M_NPHXbUGNOcMx
        echo "QG Script --> Using task id of ${ce_task_id}"
        ce_status=$(curl -s -u "${{ inputs.token }}": "${{ inputs.url }}"/api/ce/task?id=${ce_task_id} | jq -r .task.status)

        echo "QG Script --> Status of SonarQube task is ${ce_status}"
