name: 'Sonarqube Quality'
description: 'Sonarqube Quality Gate Status Checked'
inputs:
  token:
    description: "Sonar Login Token"
    required: true
  url:
    description: "Sonar Server url"
    required: true
runs:
  using: "composite"
  steps:
    - run: mvn clean verify sonar:sonar -Dsonar.host.url=${{ inputs.url }} -Dsonar.login=${{ inputs.token }}
      shell: bash

    - run: ${{ github.action_path }}/sonarScript.sh ${{ inputs.url }} ${{ inputs.token }}
      shell: bash
